"""add title to conversations

Revision ID: 265dbbb950e5
Revises: 860f199dc057
Create Date: 2026-08-06 17:04:51.118773
"""
from alembic import op
import sqlalchemy as sa


revision = '265dbbb950e5'
down_revision = '860f199dc057'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'title')
    # ### end Alembic commands ###
