"""create collections

Revision ID: 5ca7c93f4608
Revises: f455b5755d50
Create Date: 2026-08-06 13:35:35.093483
"""
from alembic import op
import sqlalchemy as sa


revision = '5ca7c93f4608'
down_revision = 'f455b5755d50'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('documents', sa.Column('collection_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'documents', 'collections', ['collection_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'collection_id')
    op.drop_table('collections')
    # ### end Alembic commands ###
