"""add token counts to prompt logs

Revision ID: a0bc98a0f661
Revises: 988014335d25
Create Date: 2026-08-06 16:34:56.827173
"""
from alembic import op
import sqlalchemy as sa


revision = 'a0bc98a0f661'
down_revision = '988014335d25'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prompt_logs', sa.Column('prompt_tokens', sa.Integer(), nullable=True))
    op.add_column('prompt_logs', sa.Column('response_tokens', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prompt_logs', 'response_tokens')
    op.drop_column('prompt_logs', 'prompt_tokens')
    # ### end Alembic commands ###
