"""add content hash to documents

Revision ID: f455b5755d50
Revises: e849f0d06d81
Create Date: 2026-08-06 13:26:24.137428
"""
from alembic import op
import sqlalchemy as sa


revision = 'f455b5755d50'
down_revision = 'e849f0d06d81'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('content_hash', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'documents', ['content_hash'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='unique')
    op.drop_column('documents', 'content_hash')
    # ### end Alembic commands ###
